# Configuracao do Banco de Dados MySQL

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sistema-bancario-spring?serverTimezone=UTC&useSSL=false}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracao do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao do Servidor
server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher